name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  backend-tests:
    name: "Go Build/Test"
    uses: ./.github/workflows/partial-tests.yml
  goreleaser:
    name: "Release"
    needs:
      - backend-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.19.3"
          cache: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
